baseURL = "https://stefangrage.github.io/skaerm.dk/"
languageCode = "da-dk"
title = "skaerm.dk"
description = "Skaerm.dk - Webbureau fra Kbh"
copyright = "&copy; skaerm"
theme = "hugo-creative-portfolio-theme"
publishDir = "docs"

[params]
style = "pink"
sidebarAbout = [
  "Vi designer og udvikler webløsninger"
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio"
  url = ""

  [[params.navlinks]]
  name = "Services"
  url = "services/"

  [[params.navlinks]]
  name = "Om"
  url = "om/"

  [[params.navlinks]]
  name = "Kontakt"
  url = "kontakt/"
